image: maven:3.8.1-jdk-11

stages:
  - build
  - quality_assurance
  - tests
  - deploy

build-project:
  stage: build
  script:
    - echo "build project"
  artifacts:
    paths:

build-backend:
  stage: build
  script:
    - cd ./backend && ./mvnw package -Dmaven.test.skip && ./mvnw test-compile

  artifacts:
    paths:
      - backend/target/

build-frontend:
    stage: build
    script:
      - cd ./frontend && echo "build frontend"
    artifacts:
      paths:

lint:
  stage: quality_assurance
  script:
    - echo "linting code structure"

test-backend-IT:
  stage: tests
  script:
    - cd ./backend && ./mvnw failsafe:integration-test

deploy:
  stage: deploy
  script:
    - echo "deploy everything"