image: maven:3.8.1-jdk-11

cache:
  paths:
    - backend/target
    - frontend/node_modules
    - frontend/dist

# necessary to turn off TSL in order to use DinD
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

stages:
  - build
  - quality_assurance
  - tests
  - deploy

build-project:
  stage: build
  script:
    - echo "build project"
  except:
    refs:
      - tags

build-backend:
  stage: build
  script:
    - cd ./backend && ./mvnw package -Dmaven.test.skip && ./mvnw test-compile
  artifacts:
    paths:
      - backend/target/
  except:
    refs:
      - tags

build-frontend:
  image: node:lts-alpine
  stage: build
  script:
    - cd ./frontend
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - frontend/dist
      - frontend/node_modules
  except:
    refs:
      - tags

build-docker-compose:
  stage: build
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - docker-privileged
  before_script:
    - apk update && apk add make
  script:
    - make dc-complete ARGS=-d
  except:
    refs:
      - tags

lint:
  stage: quality_assurance
  script:
    - echo "linting code structure"
  except:
    refs:
      - tags

IT-backend:
  stage: tests
  script:
    - cd ./backend
    - ./mvnw failsafe:integration-test failsafe:verify
  except:
    refs:
      - tags

UT-backend:
  stage: tests
  script:
    - cd backend
    - ./mvnw surefire:test
  except:
    refs:
      - tags

deploy-backend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker-privileged
  before_script:
    - apk update && apk add make
  script:
    - make deploy-backend-prod
  only:
    refs:
      - tags
  except:
    - branches

deploy-frontend:
  stage: deploy
  environment:
    name: production
    url: https://subadvisor.herokuapp.com/
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker-privileged
  before_script:
    - apk update && apk add make
  script:
    - make deploy-frontend-prod RELEASE_VERSION=$CI_COMMIT_TAG
  only:
    refs:
      - tags
  except:
    - branches