cache:
  paths:

stages:
  - build
  - quality_assurance
  - tests
  - deploy

build-project:
  stage: build
  script:
    - echo "build project"
  artifacts:
    paths:

build-backend:
  image: maven:3.8.1-jdk-11
  stage: build
  script:
    - cd ./backend && ./mvnw package
  artifacts:
    paths:
      - backend/target/*.jar

build-frontend:
    stage: build
    script:
      - cd ./frontend && echo "build frontend"
    artifacts:
      paths:

lint:
  stage: quality_assurance
  script:
    - echo "linting code structure"

test-backend-IT:
  image: openjdk:11-jre-slim-buster
  stage: tests
  script: 
    - cd backend && ./mvnw failsafe:integration-test

deploy:
  stage: deploy
  script:
    - echo "deploy everything"